<?php

/**
 * Implements hook_block_info().
 */
function ocg_hcmi_block_info() {
  $blocks = array();
  $blocks['ocg_hcmi'] = array(
    'info' => t('HCMI Searchable Catalog'),
  );
  
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ocg_hcmi_block_view($delta='') {
  $block = array();
  
  switch($delta) {
    case 'ocg_hcmi' :
      $block['content'] = ocg_hcmi_view();
      break;
  }
  
  return $block;
}

function ocg_hcmi_view() {
  $block = "<h4>Models by Primary Site</h4><div ng-app='myApp'><donut></donut></div><a id='total' href='https://hcmi-searchable-catalog.nci.nih.gov/'>Models</a>";
  
  drupal_add_js('https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js', 'external');
  drupal_add_js(drupal_get_path('module', 'ocg_hcmi') . '/js/ocg_hcmi.js');
  return $block;
}